In [1]:
import numpy as np
import pandas as pd

import statsmodels.api as sm
from statsmodels.discrete.discrete_model import Probit

from scipy.stats import norm

In [2]:
df = pd.read_csv("probit_dataset.csv")
df

,heart,lungs,liver,kidneys,stomach,spine,diabetes,hypertension,joints,ENT_organs,...,mar_st,visit_doctor,work,alcohol,smoking,phys_active,region,is_health_good,is_health_very_good,diploma
0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,1.0,0.0,1.0,1.0,1.0,0.0,1.0,0.0,0.0,0.0
1,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,1.0,0.0,...,1.0,0.0,1.0,1.0,0.0,0.0,1.0,1.0,0.0,0.0
2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,1.0,0.0,1.0,0.0,1.0,0.0,1.0,1.0,0.0,0.0
3,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,1.0,0.0,1.0,1.0,1.0,0.0,1.0,1.0,0.0,0.0
4,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,1.0,0.0,1.0,1.0,1.0,0.0,1.0,1.0,1.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4593,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,...,0.0,0.0,1.0,1.0,0.0,1.0,142.0,0.0,0.0,0.0
4594,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,1.0,0.0,1.0,1.0,0.0,0.0,142.0,0.0,0.0,0.0
4595,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,1.0,0.0,...,1.0,0.0,1.0,0.0,0.0,0.0,77.0,0.0,0.0,0.0
4596,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,1.0,0.0,1.0,0.0,0.0,0.0,77.0,0.0,0.0,0.0
4597,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,1.0,0.0,0.0,0.0,77.0,1.0,0.0,1.0

In [3]:
df.columns

Index(['heart', 'lungs', 'liver', 'kidneys', 'stomach', 'spine', 'diabetes',
       'hypertension', 'joints', 'ENT_organs', 'neurology', 'eyes', 'allergy',
       'veins', 'skin', 'oncology', 'age', 'income', 'n_child', 'sex',
       'type_area', 'invalid', 'mar_st', 'visit_doctor', 'work', 'alcohol',
       'smoking', 'phys_active', 'region', 'is_health_good',
       'is_health_very_good', 'diploma'],
      dtype='str')

In [4]:
# 1. Создаём словарь "код региона -> значение alcohol_by_region
# (Потребление алкогольной продукции на душу населения (в литрах этанола) для этого региона)"
alcohol_dict = {
    1: 96.13,
    9: 77.48,
    10: 124.47,
    12: 121.17,
    14: 102.76,
    33: 93.26,
    39: 86.51,
    45: 100.86,
    46: 132.27,
    47: 96.62,
    48: 109.46,
    52: 49.65,
    58: 109.66,
    66: 100.53,
    67: 106.43,
    70: 100.44,
    71: 111.83,
    72: 109.08,
    73: 100.53,
    77: 28.97,
    84: 109.66,
    86: 85.72,
    89: 146.86,
    92: 99.02,
    93: 113.16,
    100: 100.44,
    105: 146.86,
    106: 120.05,
    107: 120.05,
    116: 103.08,
    117: 139.63,
    129: 77.48,
    135: 109.62,
    136: 100.89,
    137: 63.11,
    138: 60.22,
    141: 80.65,
    142: 97.76,
    161: 104.41,
    200: 117.44,
}

# 2. Создаём словарь "код региона -> значение smoking_by_region
# (Объем легальных розничных продаж сигарет на душу совершеннолетнего населения для этого региона)"
smoking_dict = {
    1: 411,
    9: 402,
    10: 307,
    12: 379,
    14: 344,
    33: 295,
    39: 278,
    45: 294,
    46: 377,
    47: 327,
    48: 275,
    52: 248,
    58: 337,
    66: 361,
    67: 398,
    70: 311,
    71: 432,
    72: 313,
    73: 361,
    77: 80,
    84: 337,
    86: 432,
    89: 539,
    92: 483,
    93: 549,
    100: 311,
    105: 539,
    106: 354,
    107: 354,
    116: 384,
    117: 300,
    129: 402,
    135: 300,
    136: 334,
    137: 301,
    138: 257,
    141: 283,
    142: 458,
    161: 323,
    200: 309,
}

# 3. Создаём словарь "код региона -> значение marriages_by_region
# (Число зарегистрированных браков в расчете на 1000 населения (оперативные данные) для этого региона)"

marriage_dict = {
    1: 3.9,
    9: 7.3,
    10: 5.4,
    12: 6.1,
    14: 5.3,
    33: 5.3,
    39: 5.5,
    45: 5.9,
    46: 5.9,
    47: 6.1,
    48: 4.4,
    52: 5.1,
    58: 6.5,
    66: 6.7,
    67: 6.0,
    70: 5.5,
    71: 6.6,
    72: 5.5,
    73: 6.7,
    77: 4.6,
    84: 6.5,
    86: 5.7,
    89: 5.9,
    92: 8.0,
    93: 7.7,
    100: 5.5,
    105: 5.9,
    106: 6.5,
    107: 6.5,
    116: 6.1,
    117: 5.4,
    129: 7.3,
    135: 5.8,
    136: 5.5,
    137: 6.0,
    138: 6.6,
    141: 9.0,
    142: 5.5,
    161: 7.1,
    200: 6.3,
}


# 3. Создаём словарь "код региона -> значение phys_activity_by_region
# (Рейтинговый балл по приверженности населения ЗОЖ для этого региона)"
phys_dict = {
    1: 60.2,
    9: 81.7,
    10: 55.2,
    12: 55.8,
    14: 72.7,
    33: 76.2,
    39: 75.7,
    45: 70.2,
    46: 59.3,
    47: 64.6,
    48: 74.8,
    52: 81.5,
    58: 67.8,
    66: 46.7,
    67: 62.7,
    70: 68.9,
    71: 63.1,
    72: 72.5,
    73: 46.7,
    77: 81.8,
    84: 67.8,
    86: 58.9,
    89: 54.6,
    92: 56.9,
    93: 53.3,
    100: 68.9,
    105: 54.6,
    106: 43.2,
    107: 43.2,
    116: 66.2,
    117: 76.0,
    129: 81.7,
    135: 69.6,
    136: 81.5,
    137: 74.9,
    138: 76.0,
    141: 79.3,
    142: 80.1,
    161: 60.9,
    200: 60.1,
}


df["alcohol_by_region"] = df["region"].map(alcohol_dict)
df["smoking_by_region"] = df["region"].map(smoking_dict)
df["marriages_by_region"] = df["region"].map(marriage_dict)
df["phys_activity_by_region"] = df["region"].map(phys_dict)

df

,heart,lungs,liver,kidneys,stomach,spine,diabetes,hypertension,joints,ENT_organs,...,smoking,phys_active,region,is_health_good,is_health_very_good,diploma,alcohol_by_region,smoking_by_region,marriages_by_region,phys_activity_by_region
0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,1.0,0.0,1.0,0.0,0.0,0.0,96.13,411,3.9,60.2
1,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,1.0,0.0,...,0.0,0.0,1.0,1.0,0.0,0.0,96.13,411,3.9,60.2
2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,1.0,0.0,1.0,1.0,0.0,0.0,96.13,411,3.9,60.2
3,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,1.0,0.0,1.0,1.0,0.0,0.0,96.13,411,3.9,60.2
4,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,1.0,0.0,1.0,1.0,1.0,0.0,96.13,411,3.9,60.2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4593,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,...,0.0,1.0,142.0,0.0,0.0,0.0,97.76,458,5.5,80.1
4594,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,142.0,0.0,0.0,0.0,97.76,458,5.5,80.1
4595,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,1.0,0.0,...,0.0,0.0,77.0,0.0,0.0,0.0,28.97,80,4.6,81.8
4596,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,77.0,0.0,0.0,0.0,28.97,80,4.6,81.8
4597,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,77.0,1.0,0.0,1.0,28.97,80,4.6,81.8

In [5]:
df[["type_area"]].value_counts()

type_area
1            3403
0            1195
Name: count, dtype: int64

In [6]:
df["lnincome"] = np.log1p(df["income"])
df["gorod"] = df["type_area"].astype(float)

In [7]:
df["type_area"]

0       0
1       0
2       0
3       0
4       0
       ..
4593    0
4594    0
4595    0
4596    0
4597    0
Name: type_area, Length: 4598, dtype: int64

In [8]:
df.columns

Index(['heart', 'lungs', 'liver', 'kidneys', 'stomach', 'spine', 'diabetes',
       'hypertension', 'joints', 'ENT_organs', 'neurology', 'eyes', 'allergy',
       'veins', 'skin', 'oncology', 'age', 'income', 'n_child', 'sex',
       'type_area', 'invalid', 'mar_st', 'visit_doctor', 'work', 'alcohol',
       'smoking', 'phys_active', 'region', 'is_health_good',
       'is_health_very_good', 'diploma', 'alcohol_by_region',
       'smoking_by_region', 'marriages_by_region', 'phys_activity_by_region',
       'lnincome', 'gorod'],
      dtype='str')

In [ ]:
x_outcome = [
    "age",
    "lnincome",
    "n_child",
    "gorod",
    "invalid",
    "visit_doctor",
    "work",
]
z_behaviour = ["age", "gorod", "invalid"]
s_diploma = ["age", "invalid"]

base_regressors = {
    "diploma": s_diploma,
    "mar_st": z_behaviour,
    "alcohol": z_behaviour,
    "smoking": z_behaviour,
    "phys_active": z_behaviour,
}

extra_regressors = {
    "diploma": [],
    "mar_st": [],
    "alcohol": ["mar_st"],
    "smoking": ["mar_st"],
    "phys_active": ["mar_st"],
}

instruments = {
    "diploma": [
        "alcohol_by_region",
        "smoking_by_region",
        "marriages_by_region",
        "phys_activity_by_region",
    ],
    "mar_st": ["marriages_by_region"],
    "alcohol": ["alcohol_by_region"],
    "smoking": ["smoking_by_region"],
    "phys_active": ["phys_activity_by_region"],
}


def control_function_2spm(sex, illness, df, endog_vars, instruments):

    df_sex = df[df["sex"] == sex].copy()
    outcome = illness

    resid_cols = []

    for var in endog_vars:
        first_step_vars = (
            base_regressors[var] + extra_regressors[var] + instruments.get(var, [])
        )

        X1 = sm.add_constant(df_sex[first_step_vars])
        y1 = df_sex[var]

        probit1 = Probit(y1, X1)
        res1 = probit1.fit(disp=0)

        xb = res1.predict(X1, which="linear")
        prob = norm.cdf(xb)
        phi = norm.pdf(xb)

        generalized_resid = np.where(y1 == 1, phi / prob, -phi / (1 - prob))
        resid_name = f"{var}_gresid"
        df_sex[resid_name] = generalized_resid
        resid_cols.append(resid_name)

    X2_vars = x_outcome + endog_vars + resid_cols
    X2 = sm.add_constant(df_sex[X2_vars])
    y2 = df_sex[outcome]

    probit2 = Probit(y2, X2)
    res2 = probit2.fit(disp=0)

    resid_cols_in_model = [col for col in resid_cols if col in res2.params.index]
    if resid_cols_in_model:
        # Wald тест
        constraints = [f"{col}=0" for col in resid_cols_in_model]
        wald_test = res2.wald_test(constraints, scalar=False)
        exogeneity_pval = wald_test.pvalue
    else:
        exogeneity_pval = np.nan

    print(res2.summary())

    return {
        "coef_diploma": res2.params.get("diploma", np.nan),
        "pval_diploma": res2.pvalues.get("diploma", np.nan),
        "exogeneity_pval": exogeneity_pval,
        "n_obs": len(y2),
        "pseudo_r2": res2.prsquared,
    }


sexes = [1, 2]
illnesses = [
    "heart",
    "lungs",
    "liver",
    "kidneys",
    "stomach",
    "spine",
    "diabetes",
    "hypertension",
    "joints",
    "ENT_organs",
    "neurology",
    "eyes",
    "allergy",
    "veins",
    "skin",
    "oncology",
    "is_health_good",
]

endog_vars = ["diploma", "mar_st", "alcohol", "smoking", "phys_active"]

results = []
for sex in sexes:
    for illness in illnesses:
        res = control_function_2spm(sex, illness, df, endog_vars, instruments)
        results.append({"sex": sex, "illness": illness, **res})

                          Probit Regression Results
==============================================================================
Dep. Variable:                  heart   No. Observations:                 1926
Model:                         Probit   Df Residuals:                     1909
Method:                           MLE   Df Model:                           16
Date:                Tue, 05 May 2026   Pseudo R-squ.:                  0.1360
Time:                        16:39:43   Log-Likelihood:                -347.18
converged:                       True   LL-Null:                       -401.83
Covariance Type:            nonrobust   LLR p-value:                 6.089e-16
======================================================================================
                         coef    std err          z      P>|z|      [0.025      0.975]
--------------------------------------------------------------------------------------
age                    0.0153      0.021      0.726      0.468      -0.026       0.057
lnincome               0.0636      0.083      0.762      0.446      -0.100       0.227
n_child               -0.0260      0.066     -0.393      0.694      -0.156       0.104
gorod                 -0.1881      0.704     -0.267      0.789      -1.568       1.191
invalid                1.2221      0.858      1.424      0.154      -0.460       2.904
visit_doctor           0.4088      0.107      3.835      0.000       0.200       0.618
work                  -2.6796      5.235     -0.512      0.609     -12.939       7.580
diploma                3.3335      2.412      1.382      0.167      -1.395       8.062
mar_st                 2.9092      2.798      1.040      0.298      -2.574       8.393
alcohol               -0.9910      2.648     -0.374      0.708      -6.181       4.199
smoking               -6.3202      6.269     -1.008      0.313     -18.608       5.967
phys_active           -2.6575      1.557     -1.706      0.088      -5.710       0.395
diploma_gresid        -1.8601      1.448     -1.284      0.199      -4.699       0.979
mar_st_gresid         -1.9441      1.365     -1.424      0.154      -4.620       0.732
alcohol_gresid         0.4554      1.579      0.288      0.773      -2.639       3.549
smoking_gresid         4.0506      3.902      1.038      0.299      -3.597      11.698
phys_active_gresid     1.5105      0.888      1.701      0.089      -0.230       3.251
======================================================================================
___*100
<statsmodels.discrete.discrete_margins.DiscreteMargins object at 0x0000017B30C5FE00>
___*100
                          Probit Regression Results
==============================================================================
Dep. Variable:                  lungs   No. Observations:                 1926
Model:                         Probit   Df Residuals:                     1909
Method:                           MLE   Df Model:                           16
Date:                Tue, 05 May 2026   Pseudo R-squ.:                 0.07323
Time:                        16:39:43   Log-Likelihood:                -356.25
converged:                       True   LL-Null:                       -384.40
Covariance Type:            nonrobust   LLR p-value:                 2.172e-06
======================================================================================
                         coef    std err          z      P>|z|      [0.025      0.975]
--------------------------------------------------------------------------------------
age                   -0.0417      0.023     -1.804      0.071      -0.087       0.004
lnincome              -0.0837      0.054     -1.548      0.122      -0.190       0.022
n_child                0.0439      0.060      0.725      0.468      -0.075       0.162
gorod                 -2.6709      0.706     -3.781      0.000      -4.055      -1.287
invalid                1.0105      0.952      1.062      0.288      -0.855       2.876
visit_doctor           0.1668      0.105      1.584      0.113      -0.040       0.373
work                  16.1520      5.732      2.818      0.005       4.917      27.387
diploma                0.5317      2.444      0.218      0.828      -4.258       5.321
mar_st                -9.8472      3.082     -3.195      0.001     -15.888      -3.806
alcohol                7.0516      2.680      2.631      0.009       1.798      12.305
smoking              -22.8456      6.497     -3.516      0.000     -35.580     -10.111
phys_active            3.1469      1.776      1.772      0.076      -0.334       6.628
diploma_gresid        -0.3994      1.471     -0.272      0.786      -3.283       2.484
mar_st_gresid          3.2192      1.504      2.141      0.032       0.272       6.167
alcohol_gresid        -4.2689      1.583     -2.697      0.007      -7.371      -1.167
smoking_gresid        14.3777      4.048      3.552      0.000       6.444      22.311
phys_active_gresid    -1.8791      1.039     -1.808      0.071      -3.916       0.158
======================================================================================
___*100
<statsmodels.discrete.discrete_margins.DiscreteMargins object at 0x0000017B2CB83C20>
___*100
                          Probit Regression Results
==============================================================================
Dep. Variable:                  liver   No. Observations:                 1926
Model:                         Probit   Df Residuals:                     1909
Method:                           MLE   Df Model:                           16
Date:                Tue, 05 May 2026   Pseudo R-squ.:                 0.09283
Time:                        16:39:43   Log-Likelihood:                -263.84
converged:                       True   LL-Null:                       -290.84
Covariance Type:            nonrobust   LLR p-value:                 5.191e-06
======================================================================================
                         coef    std err          z      P>|z|      [0.025      0.975]
--------------------------------------------------------------------------------------
age                    0.0239      0.026      0.902      0.367      -0.028       0.076
lnincome              -0.0379      0.074     -0.515      0.606      -0.182       0.106
n_child               -0.0087      0.074     -0.116      0.907      -0.155       0.137
gorod                 -0.5675      0.817     -0.695      0.487      -2.168       1.033
invalid                0.6379      1.070      0.596      0.551      -1.459       2.735
visit_doctor           0.2744      0.120      2.285      0.022       0.039       0.510
work                  -0.3864      6.172     -0.063      0.950     -12.484      11.711
diploma                2.9071      2.743      1.060      0.289      -2.470       8.284
mar_st                -3.5659      2.999     -1.189      0.234      -9.444       2.312
alcohol                3.1952      3.274      0.976      0.329      -3.222       9.612
smoking               -4.6906      7.293     -0.643      0.520     -18.985       9.604
phys_active            0.7774      2.148      0.362      0.717      -3.432       4.986
diploma_gresid        -1.6591      1.651     -1.005      0.315      -4.896       1.578
mar_st_gresid          1.1513      1.447      0.795      0.426      -1.686       3.988
alcohol_gresid        -1.9254      1.943     -0.991      0.322      -5.733       1.882
smoking_gresid         3.1741      4.539      0.699      0.484      -5.722      12.070
phys_active_gresid    -0.5763      1.249     -0.461      0.645      -3.025       1.873
======================================================================================
___*100
<statsmodels.discrete.discrete_margins.DiscreteMargins object at 0x0000017B30C4C200>
___*100
                          Probit Regression Results
==============================================================================
Dep. Variable:                kidneys   No. Observations:                 1926
Model:                         Probit   Df Residuals:                     1909
Method:                           MLE   Df Model:                           16
Date:                Tue, 05 May 2026   Pseudo R-squ.:                 0.05532
Time:                        16:39:43   Log-Likelihood:                -232.62
converged:                       True   LL-Null:                       -246.24
Covariance Type:            nonrobust   LLR p-value:                   0.03887
======================================================================================
                         coef    std err          z      P>|z|      [0.025      0.975]
--------------------------------------------------------------------------------------
age                    0.0053      0.028      0.191      0.849      -0.049       0.060
lnincome               0.0242      0.090      0.270      0.787      -0.151       0.200
n_child                0.0267      0.074      0.361      0.718      -0.118       0.172
gorod                 -0.8654      0.865     -1.001      0.317      -2.560       0.829
invalid                1.8431      1.158      1.592      0.111      -0.426       4.112
visit_doctor           0.2359      0.127      1.851      0.064      -0.014       0.486
work                  -3.2403      7.545     -0.429      0.668     -18.028      11.548
diploma                4.2923      3.012      1.425      0.154      -1.611      10.195
mar_st                 2.9538      4.577      0.645      0.519      -6.016      11.924
alcohol                2.4196      3.383      0.715      0.474      -4.210       9.050
smoking              -10.3786      7.815     -1.328      0.184     -25.696       4.939
phys_active            0.3325      1.949      0.171      0.864      -3.487       4.152
diploma_gresid        -2.6425      1.821     -1.451      0.147      -6.211       0.926
mar_st_gresid         -2.0923      2.265     -0.924      0.356      -6.532       2.347
alcohol_gresid        -1.4805      2.005     -0.738      0.460      -5.410       2.449
smoking_gresid         6.5846      4.863      1.354      0.176      -2.947      16.117
phys_active_gresid    -0.1566      1.135     -0.138      0.890      -2.381       2.068
======================================================================================
___*100
<statsmodels.discrete.discrete_margins.DiscreteMargins object at 0x0000017B2CA43AA0>
___*100
                          Probit Regression Results
==============================================================================
Dep. Variable:                stomach   No. Observations:                 1926
Model:                         Probit   Df Residuals:                     1909
Method:                           MLE   Df Model:                           16
Date:                Tue, 05 May 2026   Pseudo R-squ.:                 0.03603
Time:                        16:39:43   Log-Likelihood:                -781.62
converged:                       True   LL-Null:                       -810.83
Covariance Type:            nonrobust   LLR p-value:                 9.588e-07
======================================================================================
                         coef    std err          z      P>|z|      [0.025      0.975]
--------------------------------------------------------------------------------------
age                    0.0083      0.016      0.522      0.602      -0.023       0.039
lnincome               0.0096      0.051      0.190      0.849      -0.090       0.109
n_child                0.0034      0.044      0.077      0.939      -0.084       0.090
gorod                  0.2956      0.494      0.598      0.550      -0.673       1.265
invalid               -0.1029      0.673     -0.153      0.878      -1.422       1.216
visit_doctor           0.3097      0.075      4.148      0.000       0.163       0.456
work                  -0.7431      4.005     -0.186      0.853      -8.593       7.106
diploma                0.4253      1.695      0.251      0.802      -2.897       3.747
mar_st                 0.6951      2.213      0.314      0.753      -3.641       5.032
alcohol               -1.8121      2.001     -0.905      0.365      -5.735       2.111
smoking               -1.1972      4.419     -0.271      0.786      -9.859       7.464
phys_active           -0.1736      1.181     -0.147      0.883      -2.489       2.142
diploma_gresid        -0.2998      1.024     -0.293      0.770      -2.306       1.707
mar_st_gresid         -0.4977      1.069     -0.466      0.641      -2.592       1.597
alcohol_gresid         1.0716      1.185      0.904      0.366      -1.252       3.395
smoking_gresid         0.8350      2.753      0.303      0.762      -4.561       6.231
phys_active_gresid     0.1071      0.688      0.156      0.876      -1.241       1.455
======================================================================================
___*100
<statsmodels.discrete.discrete_margins.DiscreteMargins object at 0x0000017B30C5D070>
___*100
                          Probit Regression Results
==============================================================================
Dep. Variable:                  spine   No. Observations:                 1926
Model:                         Probit   Df Residuals:                     1909
Method:                           MLE   Df Model:                           16
Date:                Tue, 05 May 2026   Pseudo R-squ.:                 0.05311
Time:                        16:39:43   Log-Likelihood:                -751.07
converged:                       True   LL-Null:                       -793.20
Covariance Type:            nonrobust   LLR p-value:                 2.817e-11
======================================================================================
                         coef    std err          z      P>|z|      [0.025      0.975]
--------------------------------------------------------------------------------------
age                    0.0090      0.016      0.569      0.569      -0.022       0.040
lnincome              -0.0379      0.046     -0.823      0.411      -0.128       0.052
n_child                0.0623      0.043      1.438      0.150      -0.023       0.147
gorod                  0.0726      0.495      0.147      0.883      -0.898       1.043
invalid               -0.1090      0.689     -0.158      0.874      -1.459       1.241
visit_doctor           0.3181      0.076      4.185      0.000       0.169       0.467
work                   1.1330      4.085      0.277      0.782      -6.874       9.140
diploma               -0.2605      1.802     -0.145      0.885      -3.793       3.272
mar_st                -1.4655      2.333     -0.628      0.530      -6.037       3.106
alcohol               -0.5167      1.978     -0.261      0.794      -4.393       3.359
smoking               -1.0098      4.447     -0.227      0.820      -9.725       7.705
phys_active           -1.1963      1.158     -1.033      0.301      -3.466       1.073
diploma_gresid        -0.0035      1.086     -0.003      0.997      -2.133       2.126
mar_st_gresid          0.7361      1.149      0.641      0.522      -1.516       2.988
alcohol_gresid         0.2675      1.173      0.228      0.820      -2.031       2.566
smoking_gresid         0.5998      2.771      0.216      0.829      -4.831       6.031
phys_active_gresid     0.7549      0.667      1.131      0.258      -0.553       2.063
======================================================================================
___*100
<statsmodels.discrete.discrete_margins.DiscreteMargins object at 0x0000017B30C5C980>
___*100
                          Probit Regression Results
==============================================================================
Dep. Variable:               diabetes   No. Observations:                 1926
Model:                         Probit   Df Residuals:                     1909
Method:                           MLE   Df Model:                           16
Date:                Tue, 05 May 2026   Pseudo R-squ.:                  0.1121
Time:                        16:39:44   Log-Likelihood:                -269.93
converged:                       True   LL-Null:                       -304.01
Covariance Type:            nonrobust   LLR p-value:                 2.095e-08
======================================================================================
                         coef    std err          z      P>|z|      [0.025      0.975]
--------------------------------------------------------------------------------------
age                    0.0292      0.024      1.197      0.231      -0.019       0.077
lnincome              -0.0336      0.064     -0.529      0.597      -0.158       0.091
n_child               -0.0332      0.075     -0.443      0.658      -0.180       0.114
gorod                  0.0557      0.761      0.073      0.942      -1.436       1.548
invalid                1.3453      0.942      1.428      0.153      -0.501       3.191
visit_doctor           0.4413      0.120      3.691      0.000       0.207       0.676
work                  -6.1590      5.861     -1.051      0.293     -17.646       5.328
diploma               -0.3662      2.658     -0.138      0.890      -5.576       4.843
mar_st                 2.3568      3.077      0.766      0.444      -3.674       8.387
alcohol                1.1240      3.000      0.375      0.708      -4.755       7.003
smoking                0.7259      6.936      0.105      0.917     -12.868      14.320
phys_active           -0.6753      1.913     -0.353      0.724      -4.425       3.074
diploma_gresid         0.2951      1.593      0.185      0.853      -2.827       3.417
mar_st_gresid         -1.0768      1.522     -0.707      0.479      -4.060       1.907
alcohol_gresid        -0.7301      1.782     -0.410      0.682      -4.223       2.763
smoking_gresid        -0.4823      4.315     -0.112      0.911      -8.940       7.975
phys_active_gresid     0.2870      1.099      0.261      0.794      -1.867       2.441
======================================================================================
___*100
<statsmodels.discrete.discrete_margins.DiscreteMargins object at 0x0000017B2CAC4E00>
___*100
                          Probit Regression Results
==============================================================================
Dep. Variable:           hypertension   No. Observations:                 1926
Model:                         Probit   Df Residuals:                     1909
Method:                           MLE   Df Model:                           16
Date:                Tue, 05 May 2026   Pseudo R-squ.:                  0.1512
Time:                        16:39:44   Log-Likelihood:                -798.58
converged:                       True   LL-Null:                       -940.89
Covariance Type:            nonrobust   LLR p-value:                 3.891e-51
======================================================================================
                         coef    std err          z      P>|z|      [0.025      0.975]
--------------------------------------------------------------------------------------
age                    0.0474      0.016      3.048      0.002       0.017       0.078
lnincome              -0.0041      0.048     -0.086      0.931      -0.098       0.090
n_child                0.0235      0.043      0.544      0.587      -0.061       0.108
gorod                  1.1579      0.500      2.318      0.020       0.179       2.137
invalid               -0.5903      0.691     -0.854      0.393      -1.945       0.764
visit_doctor           0.4304      0.074      5.819      0.000       0.285       0.575
work                  -5.7673      4.006     -1.440      0.150     -13.618       2.084
diploma               -5.0019      1.789     -2.796      0.005      -8.508      -1.496

c:\Users\Huaweii\AppData\Local\Programs\Python\Python312\Lib\site-packages\statsmodels\base\model.py:607: ConvergenceWarning: Maximum Likelihood optimization failed to converge. Check mle_retvals
  warnings.warn("Maximum Likelihood optimization failed to "
c:\Users\Huaweii\AppData\Local\Programs\Python\Python312\Lib\site-packages\statsmodels\base\model.py:607: ConvergenceWarning: Maximum Likelihood optimization failed to converge. Check mle_retvals
  warnings.warn("Maximum Likelihood optimization failed to "

                          Probit Regression Results
==============================================================================
Dep. Variable:                   skin   No. Observations:                 1926
Model:                         Probit   Df Residuals:                     1909
Method:                           MLE   Df Model:                           16
Date:                Tue, 05 May 2026   Pseudo R-squ.:                 0.07561
Time:                        16:39:45   Log-Likelihood:                -158.03
converged:                      False   LL-Null:                       -170.95
Covariance Type:            nonrobust   LLR p-value:                   0.05617
======================================================================================
                         coef    std err          z      P>|z|      [0.025      0.975]
--------------------------------------------------------------------------------------
age                    0.0260      0.037      0.708      0.479      -0.046       0.098
lnincome               0.2025      0.144      1.404      0.160      -0.080       0.485
n_child                0.0401      0.088      0.457      0.647      -0.132       0.212
gorod                 -1.5211      1.095     -1.390      0.165      -3.666       0.624
invalid               -2.8083   1.24e+04     -0.000      1.000   -2.44e+04    2.44e+04
visit_doctor           0.3947      0.150      2.627      0.009       0.100       0.689
work                  -8.4071     10.265     -0.819      0.413     -28.527      11.712
diploma               10.6865      4.188      2.552      0.011       2.478      18.895
mar_st                -0.0693      6.399     -0.011      0.991     -12.611      12.472
alcohol                8.4382      4.644      1.817      0.069      -0.664      17.540
smoking              -13.0752      9.509     -1.375      0.169     -31.712       5.562
phys_active            0.2427      2.553      0.095      0.924      -4.760       5.246
diploma_gresid        -6.5418      2.547     -2.569      0.010     -11.533      -1.550
mar_st_gresid         -1.0794      3.224     -0.335      0.738      -7.398       5.239
alcohol_gresid        -5.0425      2.734     -1.845      0.065     -10.400       0.315
smoking_gresid         8.1536      5.922      1.377      0.169      -3.454      19.761
phys_active_gresid    -0.1157      1.498     -0.077      0.938      -3.051       2.819
======================================================================================
___*100
<statsmodels.discrete.discrete_margins.DiscreteMargins object at 0x0000017B2CB2DB80>
___*100
                          Probit Regression Results
==============================================================================
Dep. Variable:               oncology   No. Observations:                 1926
Model:                         Probit   Df Residuals:                     1909
Method:                           MLE   Df Model:                           16
Date:                Tue, 05 May 2026   Pseudo R-squ.:                  0.6308
Time:                        16:39:45   Log-Likelihood:                -17.096
converged:                      False   LL-Null:                       -46.308
Covariance Type:            nonrobust   LLR p-value:                 9.620e-07
======================================================================================
                         coef    std err          z      P>|z|      [0.025      0.975]
--------------------------------------------------------------------------------------
age                   -0.0245      0.169     -0.145      0.884      -0.355       0.306
lnincome               0.9651      0.589      1.638      0.101      -0.189       2.120
n_child                0.3869      0.289      1.337      0.181      -0.180       0.954
gorod                 -2.1483      3.393     -0.633      0.527      -8.799       4.503
invalid                5.7563      7.403      0.778      0.437      -8.753      20.266
visit_doctor           6.0059   2698.936      0.002      0.998   -5283.812    5295.823
work                 -17.8665   5244.142     -0.003      0.997   -1.03e+04    1.03e+04
diploma               13.1692     18.292      0.720      0.472     -22.682      49.020
mar_st                 7.1455   4496.174      0.002      0.999   -8805.194    8819.485
alcohol               12.6376     13.515      0.935      0.350     -13.852      39.127
smoking              -38.2176     32.681     -1.169      0.242    -102.271      25.836
phys_active          -20.3311     13.550     -1.500      0.134     -46.889       6.227
diploma_gresid        -7.4512     10.861     -0.686      0.493     -28.738      13.836
mar_st_gresid         -3.9325     22.222     -0.177      0.860     -47.487      39.622
alcohol_gresid        -8.2023      8.328     -0.985      0.325     -24.525       8.120
smoking_gresid        24.4251     20.326      1.202      0.229     -15.414      64.264
phys_active_gresid    10.3626      7.009      1.479      0.139      -3.374      24.099
======================================================================================

Possibly complete quasi-separation: A fraction 0.89 of observations can be
perfectly predicted. This might indicate that there is complete
quasi-separation. In this case some parameters will not be identified.
___*100
<statsmodels.discrete.discrete_margins.DiscreteMargins object at 0x0000017B2CBE20C0>
___*100
                          Probit Regression Results
==============================================================================
Dep. Variable:         is_health_good   No. Observations:                 1926
Model:                         Probit   Df Residuals:                     1909
Method:                           MLE   Df Model:                           16
Date:                Tue, 05 May 2026   Pseudo R-squ.:                  0.1294
Time:                        16:39:45   Log-Likelihood:                -1161.9
converged:                       True   LL-Null:                       -1334.5
Covariance Type:            nonrobust   LLR p-value:                 9.726e-64
======================================================================================
                         coef    std err          z      P>|z|      [0.025      0.975]
--------------------------------------------------------------------------------------
age                    0.0083      0.014      0.597      0.550      -0.019       0.036
lnincome               0.1239      0.042      2.970      0.003       0.042       0.206
n_child               -0.0085      0.037     -0.233      0.816      -0.080       0.063
gorod                 -0.3572      0.435     -0.821      0.412      -1.211       0.496
invalid               -0.6027      0.752     -0.801      0.423      -2.077       0.872
visit_doctor          -0.5731      0.066     -8.733      0.000      -0.702      -0.444
work                  -8.6585      3.927     -2.205      0.027     -16.356      -0.961
diploma                2.2417      1.587      1.413      0.158      -0.868       5.352
mar_st                 1.5490      2.502      0.619      0.536      -3.355       6.453
alcohol                3.3492      1.790      1.871      0.061      -0.158       6.857
smoking                4.7004      3.818      1.231      0.218      -2.783      12.184
phys_active            2.8349      1.015      2.793      0.005       0.846       4.824
diploma_gresid        -1.3597      0.960     -1.417      0.157      -3.241       0.521
mar_st_gresid         -0.4810      1.238     -0.388      0.698      -2.908       1.946
alcohol_gresid        -1.9235      1.056     -1.821      0.069      -3.993       0.146
smoking_gresid        -2.9637      2.381     -1.244      0.213      -7.631       1.704
phys_active_gresid    -1.4270      0.591     -2.413      0.016      -2.586      -0.268
======================================================================================
___*100
<statsmodels.discrete.discrete_margins.DiscreteMargins object at 0x0000017B2CBE11C0>
___*100
                          Probit Regression Results
==============================================================================
Dep. Variable:                  heart   No. Observations:                 2672
Model:                         Probit   Df Residuals:                     2655
Method:                           MLE   Df Model:                           16
Date:                Tue, 05 May 2026   Pseudo R-squ.:                  0.1266
Time:                        16:39:45   Log-Likelihood:                -403.28
converged:                       True   LL-Null:                       -461.76
Covariance Type:            nonrobust   LLR p-value:                 2.114e-17
======================================================================================
                         coef    std err          z      P>|z|      [0.025      0.975]
--------------------------------------------------------------------------------------
age                    0.0238      0.047      0.509      0.610      -0.068       0.115
lnincome              -0.0601      0.028     -2.128      0.033      -0.115      -0.005
n_child                0.0643      0.062      1.042      0.297      -0.057       0.185
gorod                  0.0038      0.356      0.011      0.991      -0.695       0.702
invalid                1.3073      0.826      1.583      0.113      -0.311       2.926
visit_doctor           0.1797      0.103      1.743      0.081      -0.022       0.382
work                  -0.1525      6.324     -0.024      0.981     -12.548      12.243
diploma               -3.6883      7.064     -0.522      0.602     -17.534      10.158
mar_st                 0.4106      1.320      0.311      0.756      -2.176       2.997
alcohol               -2.0811      1.696     -1.227      0.220      -5.405       1.243
smoking                0.0341      1.660      0.021      0.984      -3.220       3.288
phys_active            0.8679      2.356      0.368      0.713      -3.750       5.485
diploma_gresid         2.2547      4.388      0.514      0.607      -6.346      10.855
mar_st_gresid         -0.2922      0.799     -0.366      0.715      -1.858       1.274
alcohol_gresid         1.1282      1.038      1.087      0.277      -0.907       3.163
smoking_gresid        -0.0691      0.922     -0.075      0.940      -1.875       1.737
phys_active_gresid    -0.3482      1.355     -0.257      0.797      -3.003       2.307
======================================================================================
___*100
<statsmodels.discrete.discrete_margins.DiscreteMargins object at 0x0000017B30C5EA80>
___*100
                          Probit Regression Results
==============================================================================
Dep. Variable:                  lungs   No. Observations:                 2672
Model:                         Probit   Df Residuals:                     2655
Method:                           MLE   Df Model:                           16
Date:                Tue, 05 May 2026   Pseudo R-squ.:                 0.05762
Time:                        16:39:45   Log-Likelihood:                -575.86
converged:                       True   LL-Null:                       -611.07
Covariance Type:            nonrobust   LLR p-value:                 8.415e-09
======================================================================================
                         coef    std err          z      P>|z|      [0.025      0.975]
--------------------------------------------------------------------------------------
age                   -0.0077      0.041     -0.186      0.852      -0.088       0.073
lnincome              -0.0321      0.026     -1.223      0.221      -0.084       0.019
n_child                0.0259      0.052      0.493      0.622      -0.077       0.129
gorod                  0.3239      0.332      0.976      0.329      -0.326       0.974
invalid                0.4629      0.761      0.608      0.543      -1.029       1.955
visit_doctor           0.2376      0.086      2.772      0.006       0.070       0.406
work                   1.4842      5.698      0.260      0.794      -9.684      12.652
diploma               -4.4906      6.440     -0.697      0.486     -17.113       8.132
mar_st                -0.1196      1.090     -0.110      0.913      -2.257       2.017
alcohol               -0.8033      1.558     -0.516      0.606      -3.857       2.250
smoking               -1.4416      1.313     -1.098      0.272      -4.015       1.131
phys_active           -0.0467      2.211     -0.021      0.983      -4.381       4.287
diploma_gresid         2.5519      4.005      0.637      0.524      -5.299      10.403
mar_st_gresid         -0.0127      0.656     -0.019      0.985      -1.299       1.274
alcohol_gresid         0.5267      0.953      0.553      0.580      -1.340       2.394
smoking_gresid         0.8592      0.729      1.179      0.239      -0.569       2.288
phys_active_gresid     0.1084      1.279      0.085      0.932      -2.398       2.615
======================================================================================
___*100
<statsmodels.discrete.discrete_margins.DiscreteMargins object at 0x0000017B2CABDB80>
___*100
                          Probit Regression Results
==============================================================================
Dep. Variable:                  liver   No. Observations:                 2672
Model:                         Probit   Df Residuals:                     2655
Method:                           MLE   Df Model:                           16
Date:                Tue, 05 May 2026   Pseudo R-squ.:                 0.08352
Time:                        16:39:45   Log-Likelihood:                -351.48
converged:                       True   LL-Null:                       -383.51
Covariance Type:            nonrobust   LLR p-value:                 1.067e-07
======================================================================================
                         coef    std err          z      P>|z|      [0.025      0.975]
--------------------------------------------------------------------------------------
age                    0.0352      0.050      0.700      0.484      -0.063       0.134
lnincome               0.0028      0.050      0.057      0.955      -0.094       0.100
n_child               -0.0531      0.072     -0.737      0.461      -0.194       0.088
gorod                  0.6329      0.377      1.678      0.093      -0.106       1.372
invalid                1.3776      0.908      1.517      0.129      -0.402       3.158
visit_doctor           0.1990      0.108      1.840      0.066      -0.013       0.411
work                  -1.2897      6.824     -0.189      0.850     -14.665      12.085
diploma               -5.8131      7.598     -0.765      0.444     -20.706       9.079
mar_st                 2.8114      1.425      1.973      0.048       0.019       5.603
alcohol               -2.2967      1.830     -1.255      0.210      -5.884       1.291
smoking                0.5179      1.576      0.329      0.742      -2.571       3.607
phys_active           -3.9107      2.372     -1.649      0.099      -8.559       0.738
diploma_gresid         3.5595      4.719      0.754      0.451      -5.690      12.809
mar_st_gresid         -1.8337      0.858     -2.138      0.033      -3.515      -0.152
alcohol_gresid         1.4283      1.122      1.273      0.203      -0.771       3.627
smoking_gresid        -0.2228      0.881     -0.253      0.800      -1.950       1.504
phys_active_gresid     2.3350      1.354      1.724      0.085      -0.320       4.990
======================================================================================
___*100
<statsmodels.discrete.discrete_margins.DiscreteMargins object at 0x0000017B2A69B560>
___*100
                          Probit Regression Results
==============================================================================
Dep. Variable:                kidneys   No. Observations:                 2672
Model:                         Probit   Df Residuals:                     2655
Method:                           MLE   Df Model:                           16
Date:                Tue, 05 May 2026   Pseudo R-squ.:                 0.04234
Time:                        16:39:45   Log-Likelihood:                -536.90
converged:                       True   LL-Null:                       -560.64
Covariance Type:            nonrobust   LLR p-value:                 5.741e-05
======================================================================================
                         coef    std err          z      P>|z|      [0.025      0.975]
--------------------------------------------------------------------------------------
age                   -0.0267      0.043     -0.618      0.537      -0.111       0.058
lnincome              -0.0114      0.026     -0.436      0.663      -0.063       0.040
n_child                0.0810      0.051      1.587      0.113      -0.019       0.181
gorod                  0.3490      0.333      1.048      0.295      -0.304       1.002
invalid                0.7179      0.807      0.890      0.374      -0.864       2.299
visit_doctor           0.3682      0.092      3.991      0.000       0.187       0.549
work                   1.5366      6.029      0.255      0.799     -10.280      13.353
diploma               -2.0727      6.909     -0.300      0.764     -15.615      11.469
mar_st                -1.1138      1.075     -1.036      0.300      -3.220       0.993
alcohol               -0.1869      1.659     -0.113      0.910      -3.439       3.065
smoking               -1.7660      1.392     -1.269      0.204      -4.493       0.961
phys_active           -1.5576      2.152     -0.724      0.469      -5.775       2.659
diploma_gresid         1.1364      4.305      0.264      0.792      -7.300       9.573
mar_st_gresid          0.4964      0.644      0.771      0.440      -0.765       1.758
alcohol_gresid         0.1046      1.014      0.103      0.918      -1.882       2.091
smoking_gresid         0.9824      0.776      1.265      0.206      -0.539       2.504
phys_active_gresid     0.9735      1.244      0.783      0.434      -1.465       3.412
======================================================================================
___*100
<statsmodels.discrete.discrete_margins.DiscreteMargins object at 0x0000017B2CB9A750>
___*100
                          Probit Regression Results
==============================================================================
Dep. Variable:                stomach   No. Observations:                 2672
Model:                         Probit   Df Residuals:                     2655
Method:                           MLE   Df Model:                           16
Date:                Tue, 05 May 2026   Pseudo R-squ.:                 0.06743
Time:                        16:39:45   Log-Likelihood:                -1110.1
converged:                       True   LL-Null:                       -1190.4
Covariance Type:            nonrobust   LLR p-value:                 6.449e-26
======================================================================================
                         coef    std err          z      P>|z|      [0.025      0.975]
--------------------------------------------------------------------------------------
age                    0.0333      0.031      1.074      0.283      -0.027       0.094
lnincome              -0.0139      0.021     -0.673      0.501      -0.055       0.027
n_child                0.0084      0.040      0.208      0.835      -0.070       0.087
gorod                  0.5339      0.258      2.067      0.039       0.028       1.040
invalid                0.8488      0.589      1.441      0.149      -0.305       2.003
visit_doctor           0.3867      0.065      5.952      0.000       0.259       0.514

In [10]:
results

[{'sex': 1,
  'illness': 'heart',
  'coef_diploma': 3.3334702160172403,
  'pval_diploma': 0.16704074154783288,
  'exogeneity_pval': array(0.1153036),
  'n_obs': 1926,
  'pseudo_r2': 0.13600503373012296},
 {'sex': 1,
  'illness': 'lungs',
  'coef_diploma': 0.5317276260308138,
  'pval_diploma': 0.8277486531036093,
  'exogeneity_pval': array(0.00043604),
  'n_obs': 1926,
  'pseudo_r2': 0.07322971610630058},
 {'sex': 1,
  'illness': 'liver',
  'coef_diploma': 2.9071095998727525,
  'pval_diploma': 0.28926984737561645,
  'exogeneity_pval': array(0.69119896),
  'n_obs': 1926,
  'pseudo_r2': 0.09282936420474619},
 {'sex': 1,
  'illness': 'kidneys',
  'coef_diploma': 4.292300000375947,
  'pval_diploma': 0.15411866347941655,
  'exogeneity_pval': array(0.56209223),
  'n_obs': 1926,
  'pseudo_r2': 0.055315168820226135},
 {'sex': 1,
  'illness': 'stomach',
  'coef_diploma': 0.4253106619323029,
  'pval_diploma': 0.8018627719706927,
  'exogeneity_pval': array(0.58761154),
  'n_obs': 1926,
  'pseudo_r2': 0.03603310216280531},
 {'sex': 1,
  'illness': 'spine',
  'coef_diploma': -0.26051910253339555,
  'pval_diploma': 0.8850784423041332,
  'exogeneity_pval': array(0.87307617),
  'n_obs': 1926,
  'pseudo_r2': 0.053112797410849955},
 {'sex': 1,
  'illness': 'diabetes',
  'coef_diploma': -0.36619432565987625,
  'pval_diploma': 0.8904208811731233,
  'exogeneity_pval': array(0.85956909),
  'n_obs': 1926,
  'pseudo_r2': 0.11209386003133315},
 {'sex': 1,
  'illness': 'hypertension',
  'coef_diploma': -5.00193932028701,
  'pval_diploma': 0.0051689966513792165,
  'exogeneity_pval': array(0.00978956),
  'n_obs': 1926,
  'pseudo_r2': 0.15124426054249018},
 {'sex': 1,
  'illness': 'joints',
  'coef_diploma': -0.1567534001067964,
  'pval_diploma': 0.9359810481743988,
  'exogeneity_pval': array(0.00846195),
  'n_obs': 1926,
  'pseudo_r2': 0.12094090175407213},
 {'sex': 1,
  'illness': 'ENT_organs',
  'coef_diploma': 1.491836929542759,
  'pval_diploma': 0.5416496595450296,
  'exogeneity_pval': array(0.0357423),
  'n_obs': 1926,
  'pseudo_r2': 0.056994995124520775},
 {'sex': 1,
  'illness': 'neurology',
  'coef_diploma': -0.24663390225538756,
  'pval_diploma': 0.9312947436829745,
  'exogeneity_pval': array(0.20702305),
  'n_obs': 1926,
  'pseudo_r2': 0.14348102869415735},
 {'sex': 1,
  'illness': 'eyes',
  'coef_diploma': -3.5131990694823285,
  'pval_diploma': 0.09698219624955091,
  'exogeneity_pval': array(0.56459302),
  'n_obs': 1926,
  'pseudo_r2': 0.06389054430386198},
 {'sex': 1,
  'illness': 'allergy',
  'coef_diploma': -0.5322584323880832,
  'pval_diploma': 0.827027625214563,
  'exogeneity_pval': array(0.99714189),
  'n_obs': 1926,
  'pseudo_r2': 0.02599366092216704},
 {'sex': 1,
  'illness': 'veins',
  'coef_diploma': -5.4544167969649315,
  'pval_diploma': 0.05538418910561017,
  'exogeneity_pval': array(0.08021117),
  'n_obs': 1926,
  'pseudo_r2': 0.09175791459365634},
 {'sex': 1,
  'illness': 'skin',
  'coef_diploma': 10.686456085632722,
  'pval_diploma': 0.010720803153540933,
  'exogeneity_pval': array(0.11182623),
  'n_obs': 1926,
  'pseudo_r2': 0.07560806489177885},
 {'sex': 1,
  'illness': 'oncology',
  'coef_diploma': 13.169209962178309,
  'pval_diploma': 0.47155033383783485,
  'exogeneity_pval': array(0.56291283),
  'n_obs': 1926,
  'pseudo_r2': 0.6308277284073465},
 {'sex': 1,
  'illness': 'is_health_good',
  'coef_diploma': 2.241670184086674,
  'pval_diploma': 0.157720183494082,
  'exogeneity_pval': array(0.00963545),
  'n_obs': 1926,
  'pseudo_r2': 0.1293821520101559},
 {'sex': 2,
  'illness': 'heart',
  'coef_diploma': -3.6883197389994455,
  'pval_diploma': 0.6015977035848414,
  'exogeneity_pval': array(0.74015039),
  'n_obs': 2672,
  'pseudo_r2': 0.1266361804560331},
 {'sex': 2,
  'illness': 'lungs',
  'coef_diploma': -4.490617076331608,
  'pval_diploma': 0.4856360484169959,
  'exogeneity_pval': array(0.57268655),
  'n_obs': 2672,
  'pseudo_r2': 0.05762226900661538},
 {'sex': 2,
  'illness': 'liver',
  'coef_diploma': -5.813093848761561,
  'pval_diploma': 0.4442464562851425,
  'exogeneity_pval': array(0.06145867),
  'n_obs': 2672,
  'pseudo_r2': 0.08352206699978149},
 {'sex': 2,
  'illness': 'kidneys',
  'coef_diploma': -2.0726972521364266,
  'pval_diploma': 0.7641901323985295,
  'exogeneity_pval': array(0.608795),
  'n_obs': 2672,
  'pseudo_r2': 0.04234007217246949},
 {'sex': 2,
  'illness': 'stomach',
  'coef_diploma': -2.793249734462285,
  'pval_diploma': 0.5697262836131101,
  'exogeneity_pval': array(0.03076895),
  'n_obs': 2672,
  'pseudo_r2': 0.06742766316254267},
 {'sex': 2,
  'illness': 'spine',
  'coef_diploma': 6.586973037623955,
  'pval_diploma': 0.18972405566828365,
  'exogeneity_pval': array(0.07504001),
  'n_obs': 2672,
  'pseudo_r2': 0.06265093523676235},
 {'sex': 2,
  'illness': 'diabetes',
  'coef_diploma': 5.929917202158073,
  'pval_diploma': 0.3207282912736594,
  'exogeneity_pval': array(0.60408023),
  'n_obs': 2672,
  'pseudo_r2': 0.10753091897497147},
 {'sex': 2,
  'illness': 'hypertension',
  'coef_diploma': 0.7476447160694275,
  'pval_diploma': 0.8760103803542675,
  'exogeneity_pval': array(0.32669088),
  'n_obs': 2672,
  'pseudo_r2': 0.17520431245998636},
 {'sex': 2,
  'illness': 'joints',
  'coef_diploma': -1.1022034018951563,
  'pval_diploma': 0.8253415963831511,
  'exogeneity_pval': array(0.01708456),
  'n_obs': 2672,
  'pseudo_r2': 0.15695631355940598},
 {'sex': 2,
  'illness': 'ENT_organs',
  'coef_diploma': -0.9943330159438935,
  'pval_diploma': 0.8648393341504244,
  'exogeneity_pval': array(0.00992837),
  'n_obs': 2672,
  'pseudo_r2': 0.01987169788939147},
 {'sex': 2,
  'illness': 'neurology',
  'coef_diploma': -3.235403997435003,
  'pval_diploma': 0.6511560755440258,
  'exogeneity_pval': array(0.41390626),
  'n_obs': 2672,
  'pseudo_r2': 0.07260120221988442},
 {'sex': 2,
  'illness': 'eyes',
  'coef_diploma': -6.021901841559397,
  'pval_diploma': 0.23819882352256916,
  'exogeneity_pval': array(3.68800702e-05),
  'n_obs': 2672,
  'pseudo_r2': 0.05924550847004595},
 {'sex': 2,
  'illness': 'allergy',
  'coef_diploma': -3.569542349292905,
  'pval_diploma': 0.552901947752745,
  'exogeneity_pval': array(0.18632484),
  'n_obs': 2672,
  'pseudo_r2': 0.03662504319028492},
 {'sex': 2,
  'illness': 'veins',
  'coef_diploma': -7.7845350226714345,
  'pval_diploma': 0.15661008577479824,
  'exogeneity_pval': array(0.05625234),
  'n_obs': 2672,
  'pseudo_r2': 0.06355908213230643},
 {'sex': 2,
  'illness': 'skin',
  'coef_diploma': 7.0980932949636175,
  'pval_diploma': 0.4784002031175376,
  'exogeneity_pval': array(0.32787982),
  'n_obs': 2672,
  'pseudo_r2': 0.03147045740231347},
 {'sex': 2,
  'illness': 'oncology',
  'coef_diploma': -4.232891854334029,
  'pval_diploma': 0.7113364602478991,
  'exogeneity_pval': array(0.85397797),
  'n_obs': 2672,
  'pseudo_r2': 0.22199861604917492},
 {'sex': 2,
  'illness': 'is_health_good',
  'coef_diploma': 12.776090871070357,
  'pval_diploma': 0.003051523368061085,
  'exogeneity_pval': array(0.0004972),
  'n_obs': 2672,
  'pseudo_r2': 0.09020116628326846}]