In [38]:
import pyreadstat
import pandas as pd
import numpy as np

In [39]:

df, meta = pyreadstat.read_sav("data/r33iall_84.sav")
df

,idind,ccredid_i,ccid_i,ccid_h,bbid_i,bbid_h,aaid_i,aaid_h,zid_i,zid_h,...,ccl43,ccl43a,ccl43as,ccm96,ccm97,ccm98,ccm99,ccm100,ccm101,ccm111
0,92.0,487801.0,1008401.0,10084.0,1008401.0,10084.0,1008401.0,10084.0,1008401.0,10084.0,...,NaN,NaN,,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,108.0,487901.0,1008801.0,10088.0,1008801.0,10088.0,1008801.0,10088.0,1008801.0,10088.0,...,NaN,NaN,,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,110.0,485703.0,1009603.0,10096.0,1009603.0,10096.0,1009603.0,10096.0,1009603.0,10096.0,...,NaN,NaN,,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,112.0,488001.0,1008901.0,10089.0,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,125.0,130301.0,1010801.0,10108.0,1010801.0,10108.0,1010801.0,10108.0,1010801.0,10108.0,...,NaN,NaN,,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
16877,65365.0,285811.0,77002411.0,770024.0,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,,NaN,NaN,NaN,NaN,NaN,NaN,NaN
16878,65366.0,284504.0,77000404.0,770004.0,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,,NaN,NaN,NaN,NaN,NaN,NaN,NaN
16879,65367.0,285006.0,77000906.0,770009.0,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,,NaN,NaN,NaN,NaN,NaN,NaN,NaN
16880,65368.0,285007.0,77000907.0,770009.0,NaN,NaN,NaN,NaN,NaN,NaN,...,1.0,NaN,,2.0,1.0,2.0,2.0,2.0,2.0,NaN
16881,65369.0,285008.0,77000908.0,770009.0,NaN,NaN,NaN,NaN,NaN,NaN,...,1.0,NaN,,2.0,2.0,2.0,2.0,2.0,2.0,NaN

In [40]:
dfw = df.copy()

outcome_vars = ["ccm20.61", "ccm20.62", "ccm20.63", "ccm20.64", "ccm20.65", "ccm20.66", "ccm20.620", "ccm20.69",
                "ccm20.610", "ccm20.611", "ccm20.612", "ccm20.613", "ccm20.615", "ccm20.616", "ccm20.617", "ccm20.618",
                "ccm20.614", "ccm20.619", "ccm20.67"]

self_assessment_health = ["ccm3"]

educ = ["cc_diplom"]

control_vars = ["cc_age", "ccj13.2", "ccj72.172", "cch5", "status", "ccm20.7", "cc_marst", "ccl5.0", "ccj1", "ccm80.0", "ccm71", "ccm113a"]

In [41]:
full_pre_list = []
full_pre_list.extend(outcome_vars)
full_pre_list.extend(self_assessment_health)
full_pre_list.extend(educ)
full_pre_list.extend(control_vars)
full_pre_list

['ccm20.61',
 'ccm20.62',
 'ccm20.63',
 'ccm20.64',
 'ccm20.65',
 'ccm20.66',
 'ccm20.620',
 'ccm20.69',
 'ccm20.610',
 'ccm20.611',
 'ccm20.612',
 'ccm20.613',
 'ccm20.615',
 'ccm20.616',
 'ccm20.617',
 'ccm20.618',
 'ccm20.614',
 'ccm20.619',
 'ccm20.67',
 'ccm3',
 'cc_diplom',
 'cc_age',
 'ccj13.2',
 'ccj72.172',
 'cch5',
 'status',
 'ccm20.7',
 'cc_marst',
 'ccl5.0',
 'ccj1',
 'ccm80.0',
 'ccm71',
 'ccm113a']

In [42]:
def transform_value(x):
    if x == 1:
        return 1
    elif x == 2:
        return 0
    else:
        return np.nan
    
def transform_health(x):
    if x == 1 or x == 2:
        return 1
    elif x == 3 or x == 4 or x == 5:
        return 0
    else:
        return np.nan
    
def transform_health_sharp(x):
    if x == 1:
        return 1
    elif x == 2 or x == 3 or x == 4 or x == 5:
        return 0
    else:
        return np.nan
    

def transform_educ(x):
    if x == 6:
        return 1
    elif x == 1 or x == 2 or x == 3 or x == 4 or x == 5:
        return 0
    else:
        return np.nan

In [43]:
dfw = dfw[full_pre_list]

for var in outcome_vars:
    dfw[var] = dfw[var].apply(transform_value)

dfw["is_health_good"] = dfw["ccm3"].apply(transform_health)
dfw["is_health_very_good"] = dfw["ccm3"].apply(transform_health_sharp)
dfw = dfw.drop(columns=self_assessment_health)
dfw["diploma"] = dfw["cc_diplom"].apply(transform_educ)
dfw = dfw.drop(columns=educ)
dfw

,ccm20.61,ccm20.62,ccm20.63,ccm20.64,ccm20.65,ccm20.66,ccm20.620,ccm20.69,ccm20.610,ccm20.611,...,ccm20.7,cc_marst,ccl5.0,ccj1,ccm80.0,ccm71,ccm113a,is_health_good,is_health_very_good,diploma
0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,...,2.0,2.0,5.0,5.0,2.0,2.0,2.0,0.0,0.0,0.0
1,0.0,0.0,0.0,0.0,0.0,1.0,1.0,1.0,1.0,1.0,...,1.0,5.0,3.0,5.0,1.0,2.0,2.0,0.0,0.0,0.0
2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,2.0,2.0,4.0,1.0,1.0,1.0,2.0,0.0,0.0,0.0
3,1.0,1.0,1.0,0.0,1.0,1.0,0.0,1.0,1.0,0.0,...,1.0,5.0,1.0,5.0,2.0,2.0,2.0,0.0,0.0,0.0
4,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,1.0,0.0,...,2.0,2.0,4.0,1.0,1.0,2.0,2.0,1.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
16877,1.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,1.0,0.0,...,2.0,2.0,3.0,5.0,2.0,2.0,2.0,0.0,0.0,1.0
16878,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,2.0,2.0,5.0,1.0,2.0,2.0,2.0,0.0,0.0,0.0
16879,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,2.0,4.0,5.0,1.0,2.0,2.0,2.0,1.0,0.0,1.0
16880,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,2.0,NaN,3.0,NaN,NaN,NaN,NaN,1.0,0.0,NaN
16881,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,2.0,NaN,3.0,NaN,NaN,NaN,NaN,1.0,0.0,NaN