In [11]:
import pyreadstat
import pandas as pd
import numpy as np

In [12]:

df, meta = pyreadstat.read_sav("data/r33iall_84.sav")
df

,idind,ccredid_i,ccid_i,ccid_h,bbid_i,bbid_h,aaid_i,aaid_h,zid_i,zid_h,...,ccl43,ccl43a,ccl43as,ccm96,ccm97,ccm98,ccm99,ccm100,ccm101,ccm111
0,92.0,487801.0,1008401.0,10084.0,1008401.0,10084.0,1008401.0,10084.0,1008401.0,10084.0,...,NaN,NaN,,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,108.0,487901.0,1008801.0,10088.0,1008801.0,10088.0,1008801.0,10088.0,1008801.0,10088.0,...,NaN,NaN,,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,110.0,485703.0,1009603.0,10096.0,1009603.0,10096.0,1009603.0,10096.0,1009603.0,10096.0,...,NaN,NaN,,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,112.0,488001.0,1008901.0,10089.0,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,125.0,130301.0,1010801.0,10108.0,1010801.0,10108.0,1010801.0,10108.0,1010801.0,10108.0,...,NaN,NaN,,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
16877,65365.0,285811.0,77002411.0,770024.0,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,,NaN,NaN,NaN,NaN,NaN,NaN,NaN
16878,65366.0,284504.0,77000404.0,770004.0,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,,NaN,NaN,NaN,NaN,NaN,NaN,NaN
16879,65367.0,285006.0,77000906.0,770009.0,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,,NaN,NaN,NaN,NaN,NaN,NaN,NaN
16880,65368.0,285007.0,77000907.0,770009.0,NaN,NaN,NaN,NaN,NaN,NaN,...,1.0,NaN,,2.0,1.0,2.0,2.0,2.0,2.0,NaN
16881,65369.0,285008.0,77000908.0,770009.0,NaN,NaN,NaN,NaN,NaN,NaN,...,1.0,NaN,,2.0,2.0,2.0,2.0,2.0,2.0,NaN

In [13]:
dfw = df.copy()

outcome_vars = ["ccm20.61", "ccm20.62", "ccm20.63", "ccm20.64", "ccm20.65", "ccm20.66", "ccm20.620", "ccm20.69",
                "ccm20.610", "ccm20.611", "ccm20.612", "ccm20.613", "ccm20.615", "ccm20.616", "ccm20.617", "ccm20.618",
                "ccm20.614", "ccm20.619", "ccm20.67"]

self_assessment_health = ["ccm3"]

educ = ["cc_diplom"]

control_vars = ["cc_age", "ccj13.2", "ccj72.172", "cch5", "status", "ccm20.7", "cc_marst", "ccl5.0", "ccj1", "ccm80.0", "ccm71", "ccm113a"]

In [14]:
full_pre_list = outcome_vars + self_assessment_health + educ + control_vars
full_pre_list

['ccm20.61',
 'ccm20.62',
 'ccm20.63',
 'ccm20.64',
 'ccm20.65',
 'ccm20.66',
 'ccm20.620',
 'ccm20.69',
 'ccm20.610',
 'ccm20.611',
 'ccm20.612',
 'ccm20.613',
 'ccm20.615',
 'ccm20.616',
 'ccm20.617',
 'ccm20.618',
 'ccm20.614',
 'ccm20.619',
 'ccm20.67',
 'ccm3',
 'cc_diplom',
 'cc_age',
 'ccj13.2',
 'ccj72.172',
 'cch5',
 'status',
 'ccm20.7',
 'cc_marst',
 'ccl5.0',
 'ccj1',
 'ccm80.0',
 'ccm71',
 'ccm113a']

In [15]:
def transform_value(x):
    if x == 1:
        return 1
    elif x == 2:
        return 0
    else:
        return np.nan
    
def transform_health(x):
    if x == 1 or x == 2:
        return 1
    elif x == 3 or x == 4 or x == 5:
        return 0
    else:
        return np.nan
    
def transform_health_sharp(x):
    if x == 1:
        return 1
    elif x == 2 or x == 3 or x == 4 or x == 5:
        return 0
    else:
        return np.nan
    

def transform_educ(x):
    if x == 6:
        return 1
    elif x == 1 or x == 2 or x == 3 or x == 4 or x == 5:
        return 0
    else:
        return np.nan
    

def transform_cont(x):
    if x == 99999997 or x == 99999998 or x == 99999999:
        return np.nan
    else:
        return x
    

def transform_area(x):
    if x == 1 or x == 2:
        return 1
    else:
        return 0
    
def transform_inv(x):
    if x == 1 or x == 5 or x == 99999996:
        return 1
    elif x == 2:
        return 0
    else:
        return np.nan
    
def transform_mar(x):
    if x == 2 or x == 3:
        return 1
    elif x == 1 or x == 4 or x == 5 or x == 6:
        return 0
    else:
        return np.nan
    
def transform_doctor(x):
    if x == 1 or x == 2 or x == 3:
        return 1
    elif x == 4 or x == 5:
        return 0
    else:
        return np.nan
    
def transform_work(x):
    if x == 1  or x == 2 or x == 3 or x == 4:
        return 1
    elif x == 5:
        return 0
    else:
        return np.nan

In [16]:
dfw = dfw[full_pre_list]

for var in outcome_vars:
    dfw[var] = dfw[var].apply(transform_value)

dfw["is_health_good"] = dfw["ccm3"].apply(transform_health)
dfw["is_health_very_good"] = dfw["ccm3"].apply(transform_health_sharp)
dfw = dfw.drop(columns=self_assessment_health)
dfw["diploma"] = dfw["cc_diplom"].apply(transform_educ)
dfw = dfw.drop(columns=educ)
dfw

,ccm20.61,ccm20.62,ccm20.63,ccm20.64,ccm20.65,ccm20.66,ccm20.620,ccm20.69,ccm20.610,ccm20.611,...,ccm20.7,cc_marst,ccl5.0,ccj1,ccm80.0,ccm71,ccm113a,is_health_good,is_health_very_good,diploma
0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,...,2.0,2.0,5.0,5.0,2.0,2.0,2.0,0.0,0.0,0.0
1,0.0,0.0,0.0,0.0,0.0,1.0,1.0,1.0,1.0,1.0,...,1.0,5.0,3.0,5.0,1.0,2.0,2.0,0.0,0.0,0.0
2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,2.0,2.0,4.0,1.0,1.0,1.0,2.0,0.0,0.0,0.0
3,1.0,1.0,1.0,0.0,1.0,1.0,0.0,1.0,1.0,0.0,...,1.0,5.0,1.0,5.0,2.0,2.0,2.0,0.0,0.0,0.0
4,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,1.0,0.0,...,2.0,2.0,4.0,1.0,1.0,2.0,2.0,1.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
16877,1.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,1.0,0.0,...,2.0,2.0,3.0,5.0,2.0,2.0,2.0,0.0,0.0,1.0
16878,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,2.0,2.0,5.0,1.0,2.0,2.0,2.0,0.0,0.0,0.0
16879,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,2.0,4.0,5.0,1.0,2.0,2.0,2.0,1.0,0.0,1.0
16880,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,2.0,NaN,3.0,NaN,NaN,NaN,NaN,1.0,0.0,NaN
16881,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,2.0,NaN,3.0,NaN,NaN,NaN,NaN,1.0,0.0,NaN

In [17]:
rename_dict = {
 'ccm20.61': 'heart',
 'ccm20.62': 'lungs',
 'ccm20.63': 'liver',
 'ccm20.64': 'kidneys',
 'ccm20.65': 'stomach',
 'ccm20.66': 'spine',
 'ccm20.620': 'diabetes',
 'ccm20.69': 'hypertension',
 'ccm20.610': 'joints',
 'ccm20.611': 'ENT_organs',
 'ccm20.612': 'neurology',
 'ccm20.613': 'eyes',
 'ccm20.615': 'allergy',
 'ccm20.616': 'veins',
 'ccm20.617': 'skin',
 'ccm20.618': 'oncology',
 'ccm20.614': 'gynecology',
 'ccm20.619': 'urine-reproductive_system',
 'ccm20.67': 'others',
 'cc_age': 'age',
 'ccj13.2': 'income',
 'ccj72.172': 'n_child',
 'cch5': 'sex',
 'status': 'type_area',
 'ccm20.7': 'invalid',
 'cc_marst': 'mar_st',
 'ccl5.0': 'visit_doctor',
 'ccj1': 'work',
 'ccm80.0': 'alcohol',
 'ccm71': 'smoking',
 'ccm113a': 'phys_active'
}

In [18]:
dfw = dfw.rename(columns=rename_dict)

dfw["age"] = dfw["age"].apply(transform_cont)
dfw["income"] = dfw["income"].apply(transform_cont)
dfw["n_child"] = dfw["n_child"].apply(transform_cont)
dfw["type_area"] = dfw["type_area"].apply(transform_area)
dfw["invalid"] = dfw["invalid"].apply(transform_inv)
dfw["mar_st"] = dfw["mar_st"].apply(transform_mar)
dfw["visit_doctor"] = dfw["visit_doctor"].apply(transform_doctor)
dfw["work"] = dfw["work"].apply(transform_work)
dfw["alcohol"] = dfw["alcohol"].apply(transform_value)
dfw["smoking"] = dfw["smoking"].apply(transform_value)
dfw["phys_active"] = dfw["phys_active"].apply(transform_value)

In [30]:
dfw.dropna()

,heart,lungs,liver,kidneys,stomach,spine,diabetes,hypertension,joints,ENT_organs,...,invalid,mar_st,visit_doctor,work,alcohol,smoking,phys_active,is_health_good,is_health_very_good,diploma
2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,1.0,0.0,1.0,1.0,1.0,0.0,0.0,0.0,0.0
4,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,1.0,0.0,...,0.0,1.0,0.0,1.0,1.0,0.0,0.0,1.0,0.0,0.0
7,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,1.0,0.0,1.0,1.0,1.0,0.0,1.0,0.0,0.0
13,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,1.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0
14,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,...,0.0,1.0,1.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
16846,0.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0
16855,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,...,0.0,0.0,0.0,1.0,1.0,0.0,1.0,0.0,0.0,0.0
16861,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,1.0,0.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0
16878,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0
16879,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,1.0